### ISSUE TITLE
doesn't play well all together

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/minimist-plugins#1]
It's seems something is wrong, or im missing something?

Doesn't play well all together `minimist-plugins`, `minimist-events` and `minimist-expand`, imo.

``` js
var minimist = require('minimist-events')(require('minimist'), {help: true})
var cli = require('minimist-plugins')(minimist)

cli
  .on('foo', console.log)
  .on('bar', console.log)
  .on('help', function () {
    console.log('help me')
  })
  .parse(process.argv.slice(2))
  .use(require('minimist-expand'))
```

expected is to show help when dont have arguments, also emit `foo` and `bar` and expand them.

```
app
# shows help

app --foo=a:b
app --foo=bar
```

maybe their order is the issue, but i tried in few more variants.

Yea it may work if i pass `*-expand` to the `postProcess` option of `*-events`.

**Comment by tunnckoCore** [comment]
We should make some trick to allow `minimist-events` to be used as plugin, thoughts? Im playing now.

ppc: you forgot to name `minimist-events` exported function, same for this package.

**Comment by jonschlinkert** [comment]
> It's seems something is wrong, or im missing something?

I'm just not finished lol. these are wip, I changed the interface for how the plugins would work halfway through, but it's only been one day! lol 

anyway, they should work better now.  [this example shows why I wanted to do all of this](https://github.com/jonschlinkert/minimist-methods/blob/master/examples/namespaces.js). It's what I was trying to accomplish from the beginning, with expand-object, etc. it's all working now :)

**Comment by jonschlinkert** [comment]
fwiw, in case that example doesn't make this clear, we will be able to do things like:

``` js
assemble.on('set', ...);
assemble.store.on('set', ...);
assemble.scaffold.on('new', ...);
```

with very little configuration (relative to what it would normally require), and all of this logic is completely reusable :)
