### ISSUE TITLE
allow pass options to control downstream plugins

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/minimist-plugins#2]
e.g.

``` js
var minimist = require('minimist')
var cli = require('minimist-plugins')(minimist, {help: true})
  //.use(require('minimist-expand'))
  .use(require('minimist-events'))
  .use(function (self) {
    console.log(self)
  })

cli.on('help', function () {
  console.log('help')
})

var argv = cli(process.argv.slice(2))
console.log(argv)
```

I reviewed all examples around these `minimist-*` packages and understand how can be done in another way, but it would be useful.

Also noticed that after last update, `.use` just pass `minimist-plugins`s **this**, which is confusing - you cant access argv directly, you cant control/modify it.

I think it would be better plugin's context to be that `self` and arguments to be:
- `argv` - object, parsed by minimist
- `args` - array, coming directly from cli (process.argv)
- `opts` - object, coming from `.parse` and merged with these from initializing

``` js
var cli = require('minimist-plugins')(minimist, {help: true})
```

Also if we uncomment `minimist-expand` plugin, we cant accest his job in the next plugins, only in the end from `argv`. Also want to point that i noticed how this can be done - passing it to postProcess option of `minimist-events`, but it's not so comfortable.

Yea we can do 

``` js
var minimist = require('minimist')
var cli = require('minimist-events')(minimist, {
  help: true,
  postProcess: require('minimist-expand')
})

cli.on('help', function () {
  console.log('help')
})
var argv = cli(process.argv.slice(2))
console.log(argv)
```

But then `minimist-plugins` isn't needed. And still, we won't be able to access them in the plugins stack.

``` js
var minimist = require('minimist')
var events = require('minimist-events')(minimist, {
  help: true,
  postProcess: require('minimist-expand')
})
var cli = require('minimist-plugins')(events)
  .use(function (self) {
    console.log(self)
  })

cli.on('help', function () {
  console.log('help')
})
var argv = cli(process.argv.slice(2))
console.log(argv)
```
## Proposal Look
- would make `.use` more usable
- `.use` would make more sense
- cleans the above examples tricky stuff 
- more control of plugins
- more control on options, parsed `argv` object and incoming `process.argv` array

``` js
var minimist = require('minimist')
var cli = require('minimist-plugins')(minimist, {help: true, abc: 'foo'})
  .use(require('minimist-events'))
  .use(require('minimist-expand'))
  .use(function (argv, args, opts) {
    console.log(this) // access to `.on`, `.off`, `.emit` and etc

    console.log(argv) // object, parsed and expanded minimist
    //=> { _: [], set: { a: 'b' }, s: { a: 'b' }, g: true, global: true }

    console.log(args) // array, coming from cli
    //=> ['--set=a:b', '-g']

    console.log(opts)
    //=> {help: true, abc: 'foo', qux: 'charlike', alias: {
    //   s: 'set',
    //   g: 'global'
    // }}

    if (argv.version || argv.v) {
      this.emit('version', require('./package.json').version)
    }
    // even, it won't be needed to return anything or `this`
    // it will do the job automatically (returning `this` internally)
    return this
  })
  .use(function moreDetectsForHelp (argv) {
    // because `minimist-events` would emit
    // only if no falgs/commands,
    // and only if `opts.help:true`
    if (argv.h || argv.help) {
      this.emit('help')
    }
  })


cli
  .on('help', function () {
    console.log('help')
  })
  .on('version', function (version) {
    console.log('v' + version)
  })

var argv = cli(process.argv.slice(2), {
  alias: {
    s: 'set',
    g: 'global'
  },
  qux: 'charlike'
})

console.log(argv)
//=> { _: [], set: { a: 'b' }, s: { a: 'b' }, g: true, global: true }
```

And actually, i did most of the `minimist-plugins` side of the things, but not in 20 SLOC in 30-35.
But but cant deal with the `minimist-events` and `minimist-expand` stuff, lol.

**Comment by jonschlinkert** [comment]
> you cant access argv directly, you cant control/modify it.

I agree, it would be useful. I was saying the same thing to @doowb. 

> `.use(function (argv, args, opts)`

that is **exactly** what I was thinking earlier. I'd be happy with that. it would be really useful

> Also want to point that i noticed how this can be done - passing it to postProcess option of minimist-events, but it's not so comfortable.

yeah, that's really only useful if you're not using minimist-plugins AND you want to ensure that the args are post-processed before any events are emitted.

> But but cant deal with the minimist-events and minimist-expand stuff, lol.

can you clarify? not sure what you mean there

**Comment by tunnckoCore** [comment]
Said that, if we do to look like this building plugins and changing/updating/fixing the already existing plugins like `minimist-events` would be easy. Because we'll have access to `this` on which we can detect how to do the things and what to return. E.g.

**Comment by tunnckoCore** [comment]
> yeah, that's really only useful if you're not using minimist-plugins AND you want to ensure that the args are post-processed before any events are emitted.

Agreed.

Said that, if we do it to look like this building plugins and changing/updating/fixing the already existing plugins like `minimist-events` would be easy. Because we'll have access to `this` on which we can detect how to do the things and what to return. 

Say we are in the `minimist-events` (much like @helpers stuff detecting assemble, verb, etc)

``` js
module.exports = function minimistEvents(argv, args, opts) {
  if (this.use && this.plugins) {
    // it is used as plugin, so that is easy
    return this
  }

  // - `argv` is `minimist` function
  // - `args` options

  // and we should return proxy
  // as it is currently
}
```

And if have named plugins we can detect the things more easily.

> can you clarify? not sure what you mean there

Just they dont work.
I'll give example in a bit, i deleted all before few hours when you push `0.2.0` lol.

**Comment by doowb** [comment]
When we were going over this yesterday, I threw out the idea of the leveldb ecosystem that has "plugins" that modify or add functionality to the base `level` module. What we did was change up the `.use` method to basically make a shortcut for doing a bunch of chained require statements.

This allows each plugin to return the original `minimist` object that it receives or create a wrapper (`proxy`) around `minimist` and forward `minimist` functionality along.

doing this:

``` js
var minimist = require('minimist');
var methods = require('minimist-methods');
var cli = require('minimist-plugins')(minimist)
  .use(require('minimist-expand'))
  .use(require('minimist-events'))
  .use(methods(app))
  .use(methods('one', one))
  .use(methods('two', two))
```

should be the equivalent of doing:

``` js
var minimist = require('minimist');
var methods = require('minimist-methods');

minimist = require('minimist-expand')(minimist);
minimist = require('minimist-events')(minimist);
minimist = methods(app)(minimist);
minimist = methods('one', one)(minimist);
minimist = methods('two', two)(minimist);
```

what happens is that each plugin has no knowledge of any other plugins, it just uses the minimist api (`minimist(process.argv.slice(2))`) to parse the commandline arguments, then do something additional to them.

Because the plugins return an api that looks like `minimist`, the other plugins can use it.

All that being said... we can make `use` work more like `middleware` where the `minimist-plugins` first calls `minimist` and parses the `argv`, then passes those along to each middleware like in the example above.

This will work and if the middleware always expect to get `argv`, and can be used standalone like:

``` js
var minimist = require('minimist');
var events = require('minimist-events');

var argv = minimist(process.argv.slice(2));

// returns a middleware function with emitter methods
var cli = events();
// use an emitter method
cli.on('foo', console.log);
// this is the actual middleware call
cli(argv, {});
```

After typing all this out, I just noticed this in your last example: 

> // - `argv` is `minimist` function

Which is different than the previous example (which my comments were based on).
I like the idea of pass in "minimist" to each plugin, which might be a proxy function from a previous plugin, but it shouldn't matter to that plugin because all it wants to do is call `minimist()` and get `argv` back.

My 2¢, we just need to document how to create a `minimist-plugin` plugin ;)

**Comment by tunnckoCore** [comment]
> After typing all this out, I just noticed this in your last example:

With that i mean the parsed `process.argv` thing, as in your examples and as your thoughts - passing parsed `argv` to each plugin.

But yea, Im agree with you :+1: 

From your first example (with `.use`), from where you thinking to pass `process.argv`? - from `.parse` or?

**Comment by jonschlinkert** [comment]
we can do either... https://github.com/jonschlinkert/minimist-expand/blob/master/index.js#L14-L17

**Comment by jonschlinkert** [comment]
I know we need to do more logic, I'm just saying we should be able to handle either scenario - with minimist expected, or argv

**Comment by tunnckoCore** [comment]
> we can do either...

:+1: yea i changed it to  

``` js
  // plugin signature
  var plugin = this && this.minimist && this.use && this.parse
  if (plugin) {
    this.argv = expandArgs(this.argv)
    return this
  }
```

and it works (with refactored `minimist-plugins`)

And that's why, because im 100% for plugins to have `this` context. i just cant do `minimist-events` to work .. ;d

**Comment by jonschlinkert** [comment]
> i just cant do minimist-events to work .. ;d

you have to make sure the emitter is being forwarded, it's tricky.

**Comment by doowb** [comment]
I just saw your refactor before this comment, and now I remember why we were doing plugins like this....
It was for the forwarding because we were returning basically a new object (function) and we needed to ensure that it could be created for all the tests.

But with the changes, I think since `MinimistPlugins` is a new Object, then the `minimist-events` would wrap `this` instead of `minimist`: `Emitter(this)`, then you can do something like....

``` js
var cli = require('minimist-plugins')(require('minimist'))
  .use(require('minimist-expand'))
  .use(require('minimist-events'));

cli.on('foo', console.log);
cli.parse();
```

Then I don't think we need all the forwarding stuff because the `this` object is just being modified.

Blah... I'll keep what i just wrote, but I realized that you're caching the plugin inside of `.use` and only calling them when doing `.parse()` so `minimist-events` doesn't have a chance to add `.on()` before `.parse()`. We might need to do:

``` js
MinimistPlugins.prototype.use = function (plugin) {
  var fn = plugin.call(this, this.minimist);
  this.plugins.push(fn);
  return this;
};
```

Now a plugin will look something like this:

``` js
module.exports = function events (minimist) {
  // do a check to see if `this` is an instance of `MinimistPlugins` somehow
  // if it is, return a middleware function
  Emitter(this);
  return function (argv, args, opts) {
    // do emitting
    return this;
  };
};
```

**Comment by jonschlinkert** [comment]
I'm not sure if calling the plugin immediately in `use` like that will work. we might need to do the same thing we did in `forward-object`. I guess I'm struggling to see why we need to do all of this, when it seems like we should be able to just pass the args from the previous plugin as the second argument to the "current" plugin. why is this any different than any other plugin system? 

actually, why don't we look at using `ware` for this?

**Comment by tunnckoCore** [comment]
> Then I don't think we need all the forwarding stuff because the this object is just being modified.

and 

> Blah... I'll keep what i just wrote, but I realized

exactly :D 

The things would be easy, i tried it, if `.parse` is first thing then N plugins, but I just didn't like the signature

``` js
var cli = require('minimist-plugins')(require('minimist'), options)
  .parse(process.argv.slice(2), options)
  .use(require('minimist-events'))
  .use(require('minimist-expand'))
  .use(function moreHelp () {
     if (argv.h || argv.help) {
       this.emit.apply(this, ['help'].concat(arguments))
     }
  })
  .use(function version () {
     if (argv.v || argv.version) {
       this.emit.apply(this, ['version'].concat(arguments))
     }
  })
  .on('help', function (argv, args, opts) {
    console.log('the help')
  })
  .on('version', function (argv, args, opts) {
    console.log('v', require('./package.json').version)
  })
  .on('*', console.log)
```

So yea, that would be cool and will work - events will work, will have context and will be able to emit/on/off/etc from the plugins. Also they would be easy to write with simple detect like _"if this && this.plugins && this.use && this.parse -> then the thing is used as plugin, otherwise as standalone"_

> actually, why don't we look at using ware for this?

cuz is big and not okey. better try https://github.com/tunnckoCore/benz and https://github.com/tunnckoCore/vez , especially `vez` is the same thing as `ware` - most awesome middleware composition you ever seen! but only async, the problem is `sync` is hard to be detected, because `promises` and `streams` looks like sync functions

The best would be to just use your www.npm.im/plugins, or to implement something like it, smaller.

---

https://github.com/tunnckoCore/useware
https://github.com/tunnckoCore/useware-context

for flexible `.use`

**Comment by tunnckoCore** [comment]
Cool. I've just fix 2-3 lines from the master branch and it works great LOL. But again.. `use`es should be after parsing e.g. `cli(process.argv.slice(2)).use().use()`

**Comment by jonschlinkert** [comment]
> cuz is big and not okey

ware is heavily used and has a pretty small footprint. it would be great to not have to debate everything so much ;)

**Comment by jonschlinkert** [comment]
> it works great LOL

it only works great if all events are emitted by the correct objects at the correct times. e.g. [this should be working](https://github.com/jonschlinkert/minimist-methods/blob/master/examples/namespaces.js)

**Comment by tunnckoCore** [comment]
Ooookey, i realized why `minimist-events` dont work as plugin and what is the paradox.
It's because plugins are executed when `cli()` is called and actually `cli` then become event emitter and after it's calling you can listen for events and emit events. The paradox is here. When the plugin `minimist-events` is executed there's no listeners for emits that he calls. That's the problem with this strategy.

But with other strategy, where we call plugins immediately when they are included, e.g.

``` js
MinimistPlugins.prototype.use = function (plugin) {
  var fn = plugin.call(this, this.minimist);
  this.plugins.push(fn);
  return this;
};
```

we won't have parsed `argv` in each plugin because we will execute them before we execute minimist, which makes them unusable.

And every system got the first strategy - every plugin is just pushed to some array and after that we just calls the plugin stack over something and with some context.

Other than that.. i made other things to work (and `minimist-methods`) - implementations are not class based as this PR. I will push examples and code to https://github.com/tunnckoCore/minimist-stuff in a bit to show the process and all things done.

**Comment by jonschlinkert** [comment]
:+1: sounds good

**Comment by tunnckoCore** [comment]
i think it's done https://github.com/tunnckoCore/minimist-stuff, review and run examples and comment
- `minimist-events` cant be plugin, `help` and `end` have also plugin signature if they aren't specified from `--help` or `--end`, so there could be implemented `end` or `help` plugins
- every plugin is `minimist` and `options`
- every plugin have context, almost only `this.argv`
- every `options` are merged and passed to `minimist`
- every plugin can accept other plugin, because it is `minimist`
- `visit` is without namespaces, it can be implemented, or can have separate packages `minimist-visit` and `minimist-namespace(s)`
- `visit` have `visit(minimist, opts, app)` or if dont have third argument searches `opts.app`, which can be defined from options from other plugin, cuz they all are merged and available in all plugins already merged
- `visit` can work standalone and if used as plugin you should use `minimist-events`
  - see last example below

``` js
var minimist = require('minimist')
minimist = require('minimist-expand')(minimist, opts)
minimist = require('minimist-events')(minimist, opts)
minimist = require('minimist-visit')(minimist, {app: app})
minimist = require('minimist-plugins')(minimist, opts)

minimist(process.argv.slice(2), {baz: 'qux'})

console.log(minimist.argv)
```

if you pass different option in each plugin, they all are available to each plugin and they all are passed to minimist

**`visit` as plugin**

``` js
var App = require('./app').App
var app = new App()
var minimist = require('minimist')

var lib = require('../index')
var events = lib.events(minimist, {app: app})
var cli = lib.plugins(events, {help: true}).use(lib.visit)

cli
  .on('set', console.log.bind(console, '[set]'))
  .on('get', console.log.bind(console, '[get]'))
  .on('help', function () {
    console.log('usage help')
  })

// node example.js --set=foo:bar // shows set
// node example.js // shows help
cli(process.argv.slice(2), {toBoolean: true})

console.log(cli)
console.log('====')
console.log(cli.argv)
console.log('====')
console.log(app.cache) // also, `app` is event emitter

```

**Comment by jonschlinkert** [comment]
> minimist-events cant be plugin

events was the main reason I created all of this. I'm not sure what that means.

> visit is without namespaces, it can be implemented

this was the second reason I created all of this - to get the namespaced events for "sub-applications". 

to reiterate what I said above:

> it only works great if all events are emitted by the correct objects at the correct times. e.g. this should be working

Everything in that file is working as expected currently. That was my goal. You're telling me that the two main features: events and namespaced events, don't work in your changes lol. Why is that more desirable?

**Comment by tunnckoCore** [comment]
> Why is that more desirable?

events cant be used as plugin, because the architecture of plugin system and every plugins system. your examples can be accomplished in other way, run and view the `examples/` dir.
namespaces is few lines to add to `visit`. Last example in the comment above is great view of that it can do what you want.

**Comment by tunnckoCore** [comment]
@jonschlinkert 

you can just do

```js
/* jshint asi:true */

'use strict'

var App = require('./app').App
var app = new App()
var lib = require('../index')

var minimist = require('minimist-events')(require('minimist'))
var cli = require('minimist-plugins')(minimist, {help: true})


cli
  .on('set', console.log.bind(console, '[set]'))
  .on('get', console.log.bind(console, '[get]'))
  .on('help', function () {
    console.log('usage help')
  })
  .on('end', function () {
    console.log(app.cache)
  })

cli
  .use(require('minimist-exapand'))
  .use(require('minimist-methods'))

cli(process.argv.slice(2), {toBoolean: true})

```

and all will work. just we need to add `.namespace` to the visit

**Comment by tunnckoCore** [comment]
[examples/visit.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/examples/visit.js) works as you want

**Comment by jonschlinkert** [comment]
okay, let me review more

**Comment by tunnckoCore** [comment]
new mixed example added [examples/passthrough.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/examples/passthrough.js), notice the options passing.

**Comment by tunnckoCore** [comment]
Or [examples/events-namespaces.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/examples/events-namespaces.js) workaround. (but `toEmitter` should be able to accept functions, because `self/this` (the context) is actually minimist proxy function, not object)
It's easy, cuz event handlers are with minimist context and looks like plugins. But you cant have namespaces as plugins because same reason as you can't give `minimist-events` as plugin.

I think namespacing can be built-in in `minimist-events` through option or separate package (im not sure) e.g. [lib/namespace.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/lib/namespace.js)
Not namespaced mapping (e.g. `methods(app)`) can be seen in [examples/visit.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/examples/visit.js)

edit: also checkout [examples/namespace.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/examples/namespace.js) and [lib/namespace.js](https://github.com/tunnckoCore/minimist-stuff/blob/master/lib/namespace.js) "plugin".
